name: Release

on:
  push:
    tags:
      - "*"
  pull_request:
    branches: [main]

jobs:
  release:
    name: Release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, macos]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/blackd-client
            asset_name: blackd-client_linux
          - name: macos
            os: macos-latest
            artifact_name: target/release/blackd-client
            asset_name: blackd-client_macos

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --release --locked

      - name: Upload binaries to release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}

      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/*
          draft: ${{ startsWith(github.ref, 'refs/tags/') != true }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
